# -*- coding: utf-8 -*-
"""09_WeekChallenge_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cA0UG8egzSauyOm_cFwAhcb1CtmorLvn

# 양자화된 모델을 GGUF 포맷으로 변환하고 Llama.cpp로 추론해 보세요.
"""

pip install -q -U transformers accelerate peft trl datasets
pip install -U torchao

# Qwen 모델 사용

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    dtype="auto",
    device_map="auto",
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

# LoRA 어댑터 설정

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

pip install trl

from trl import SFTConfig, SFTTrainer
from datasets import load_dataset

dataset = load_dataset("trl-lib/Capybara", split="train[:200]")

trainer = SFTTrainer(
    model=model,
    args=SFTConfig(
        output_dir="./lora-output",
        max_steps=20,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        warmup_ratio=0.03,
        logging_steps=5,
        fp16=True,
        report_to="none",
    ),
    train_dataset=dataset,
    processing_class=tokenizer,
)

# 어댑터 파라미터 학습
trainer.train()

from peft import PeftModel

# 학습된 LoRA 어댑터 저장
model.save_pretrained("./lora_adapter")
tokenizer.save_pretrained("./lora_adapter")

base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    dtype="auto",
    device_map="auto",
)

inference_model = PeftModel.from_pretrained(base_model, "./lora_adapter")

# 추론 예시
inputs = tokenizer("MMORPG는", return_tensors="pt").to("cuda")
outputs = inference_model.generate(**inputs, max_new_tokens=80)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

